name = "joho-studio-api"
main = "src/index.js"
compatibility_date = "2026-04-14"

[[d1_databases]]
binding = "DB"
database_name = "database1"
database_id = "170f70f6-090c-4211-b6b7-d195861c5069"

[[r2_buckets]]
binding = "STRIPS_BUCKET"
bucket_name = "atlas-stamps"
preview_bucket_name = "atlas-stamps"

[vars]
R2_PUBLIC_BASE_URL = "https://fbb8d28006d9a107c7451259eb560a45.r2.cloudflarestorage.com/atlas-stamps"
MAPBOX_PUBLIC_TOKEN = ""
OPEN_LIBRARY_QUERY = "design engineering art photography architecture film typography"
